# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\61980\Desktop\demo\ac.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ReComboBox(QtWidgets.QComboBox):

    clicked = QtCore.pyqtSignal()

    def mouseReleaseEvent(self, QMouseEvent):
        self.clicked.emit()

class UiComboBox(object):
    def setupUi(self, parent=None):
        self.grid = QtWidgets.QHBoxLayout(parent)
        self.grid.setContentsMargins(0, 0, 0, 0)
        self.grid.setSpacing(0)
        self.frame_46 = QtWidgets.QFrame(parent)
        # self.frame_46.setMinimumSize(QtCore.QSize(200, 40))
        self.frame_46.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_46.setMaximumSize(QtCore.QSize(150, 40))
        self.frame_46.setStyleSheet(""".QFrame{
                                    /*border-radius:10px;*/
                                    background-color: #e6e5e5;
                                    }
                                    """)
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)

        self.gridLayout_31 = QtWidgets.QGridLayout(self.frame_46)
        self.gridLayout_31.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_31.setSpacing(2)

        self.frame_49 = QtWidgets.QFrame(self.frame_46)
        self.frame_49.setStyleSheet(""".QFrame{
                                    border-radius:5px;
                                    background-color: rgb(255, 255, 255);
                                    }
                                    """)
        self.frame_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)

        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_49)
        self.horizontalLayout_33.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_33.setSpacing(0)

        self.frame_50 = QtWidgets.QFrame(self.frame_49)
        self.frame_50.setStyleSheet("border-radius:0px")
        self.frame_50.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)

        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_50)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setSpacing(0)

        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setSpacing(0)

        self.comboBox = ReComboBox(self.frame_50)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 500))
        self.comboBox.setStyleSheet("""
                                    QComboBox::drop-down {
                                        subcontrol-origin: padding;
                                        subcontrol-position: top right;
                                        width: 30px;border-left-width:0px;
                                        border-left-color: darkgray;
                                        border-left-style: solid;
                                        border-top-right-radius: 3px;
                                        border-bottom-right-radius: 3px;
                                        }
                                    QComboBox::down-arrow {
                                        image: url(:/newPrefix/ims/03_close.png);
                                        }
                                    border:none;
                                    color:  #808080;background-color: rgb(255, 255, 255);
                                    border-color: rgb(211, 228, 255);
                                    selection-background-color: #4a637c;
                                """)

        self.horizontalLayout_35.addWidget(self.comboBox)
        self.horizontalLayout_35.setStretch(0, 3)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_33.addWidget(self.frame_50)
        self.gridLayout_31.addWidget(self.frame_49, 0, 1, 1, 1)

        self.grid.addWidget(self.frame_46)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QFrame()
    ui = UiComboBox()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
