# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\61980\Desktop\demo\ag.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from resources import my_imgs_rc

class Ui_StartFace(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 768)

        Form.setMinimumSize(QtCore.QSize(1024, 768))

        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("QFrame#frame{\n"
"border-image: url(:/newPrefix/imgs/20_bg-02.png);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_9)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(300, 61))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.show_0 = QtWidgets.QFrame(self.frame_7)
        self.show_0.setStyleSheet("border-image: url(:/newPrefix/imgs/19_gene2.png);")
        self.show_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.show_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.show_0.setObjectName("show_0")
        self.horizontalLayout.addWidget(self.show_0)
        self.show_1 = QtWidgets.QFrame(self.frame_7)
        self.show_1.setStyleSheet("border-image: url(:/newPrefix/imgs/19_gene2.png);")
        self.show_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.show_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.show_1.setObjectName("show_1")
        self.horizontalLayout.addWidget(self.show_1)
        self.show_2 = QtWidgets.QFrame(self.frame_7)
        self.show_2.setStyleSheet("border-image: url(:/newPrefix/imgs/19_gene2.png);")
        self.show_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.show_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.show_2.setObjectName("show_2")
        self.horizontalLayout.addWidget(self.show_2)
        self.show_3 = QtWidgets.QFrame(self.frame_7)
        self.show_3.setStyleSheet("border-image: url(:/newPrefix/imgs/19_gene2.png);")
        self.show_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.show_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.show_3.setObjectName("show_3")
        self.horizontalLayout.addWidget(self.show_3)
        self.show_4 = QtWidgets.QFrame(self.frame_7)
        self.show_4.setStyleSheet("border-image: url(:/newPrefix/imgs/19_gene2.png);")
        self.show_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.show_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.show_4.setObjectName("show_4")
        self.horizontalLayout.addWidget(self.show_4)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout.addWidget(self.frame_10)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 3)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "安智因PCR定性结果自动化分析软件"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_StartFace()
    ui.setupUi(Form)
    Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
    Form.show()
    sys.exit(app.exec_())
