# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ab.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QHeaderView, QItemDelegate

class ReLineEdit(QtWidgets.QLineEdit):

    def leaveEvent(self, event):
        self.setStyleSheet("border:none")
    def enterEvent(self, a0: QtCore.QEvent) -> None:
        self.setStyleSheet("color:#0055ff;border:none")


class EmptyDelegate(QItemDelegate):
    def __init__(self, parent):

        super(EmptyDelegate, self).__init__(parent)


    def createEditor(self, QWidget, QStyleOptionViewItem, QModelIndex):
        return None
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
                                        "    background-color:white;    \n"
                                        "    border:1px solid #E0DDDC;   \n"
                                        "}\n"
                                        "QHeaderView::section {\n"
                                        "    background-color:white;    \n"
                                        "    border:1px solid #E0DDDC;  \n"
                                        "    height:20px;               \n"
                                        "}\n"
                                        "QTableView{\n"
                                        "    color: rgb(0, 0, 0);\n"
                                        "    border: 1px solid #E0DDDC;        \n"
                                        "}\n"
                                        "\n"
                                        "")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(3)
        # 列宽自动分配
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        # 行高自动分配
        self.tableWidget.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
        # 设置纵向表头隐藏
        self.tableWidget.verticalHeader().setVisible(False)
        # 设置纵向表头宽度
        # self.tableWidget.verticalHeader().setFixedWidth(20)
        #　设置横向表头高度
        self.tableWidget.horizontalHeader().setFixedHeight(40)
        # 设置表头内容
        list = ['机器编号', '机器类型', '操作']
        self.tableWidget.setHorizontalHeaderLabels(list)
        # 设置表头不可点击
        self.tableWidget.horizontalHeader().setSectionsClickable(False)
        # 设置行高使用固定值
        self.tableWidget.verticalHeader().setSectionResizeMode(QHeaderView.Fixed)

        newItem = QtWidgets.QTableWidgetItem("7500-1")  # 添加张三 到（0，0）
        self.tableWidget.setItem(0, 0, newItem)

        comBox = QtWidgets.QComboBox()  # 新建一个下拉组件
        comBox.addItem("7500")
        comBox.addItem("7600")
        # comBox.currentIndexChanged.connect(self.comboxSelect)  # 绑定combox select 事件
        self.tableWidget.setCellWidget(0, 1, comBox)  # 添加下拉组件到列表（0，1）

        self.frame1 = QtWidgets.QWidget()
        # self.frame1.setMaximumWidth(80)
        self.hboxlayout = QtWidgets.QHBoxLayout(self.frame1)
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(0)

        line = ReLineEdit("修改")  # 新建一个按钮
        line.setStyleSheet("border:none;")
        line.setAlignment(QtCore.Qt.AlignRight)
        line.setMinimumHeight(40)
        line.setFocusPolicy(QtCore.Qt.NoFocus)

        line1 = QtWidgets.QLineEdit("/")  # 新建一个按钮
        line1.setStyleSheet("border:none;")
        line1.setMaximumWidth(10)
        line1.setAlignment(QtCore.Qt.AlignCenter)
        line1.setMinimumHeight(40)
        line1.setFocusPolicy(QtCore.Qt.NoFocus)

        line2 = ReLineEdit("删除")  # 新建一个按钮
        line2.setStyleSheet("border:none;")
        line2.setMinimumHeight(40)
        # 设置不可编辑
        line2.setFocusPolicy(QtCore.Qt.NoFocus)

        # searchBtn.setStyleSheet("QPushButton{margin:3px};")
        self.hboxlayout.addWidget(line)
        self.hboxlayout.addWidget(line1)
        self.hboxlayout.addWidget(line2)
        # searchBtn.clicked.connect(self.butClick)  # 绑定按钮点击事件
        self.tableWidget.setCellWidget(0, 2, self.frame1)  # 添加按钮到列表（0，2）
        # 设置某一列不可编辑
        # self.tableWidget.setItemDelegateForColumn(0,EmptyDelegate(self.tableWidget)) # 设置第二列不可编辑


        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())